// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Data;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Data.Configurations
{
    public partial class TasksConfiguration : IEntityTypeConfiguration<Tasks>
    {
        public void Configure(EntityTypeBuilder<Tasks> entity)
        {
            entity.HasKey(e => e.TaskId);

            entity.HasIndex(e => e.Task1TaskId, "IX_Tasks_Task1TaskID");

            entity.Property(e => e.TaskId).HasColumnName("TaskID");

            entity.Property(e => e.RecurrenceId).HasColumnName("RecurrenceID");

            entity.Property(e => e.Task1TaskId).HasColumnName("Task1TaskID");

            entity.HasOne(d => d.Task1Task)
                .WithMany(p => p.InverseTask1Task)
                .HasForeignKey(d => d.Task1TaskId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tasks> entity);
    }
}
